name: "Picasso API"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.PGUSER }}
          POSTGRES_PASSWORD: ${{ env.PGPASSWORD }}
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports: ["6379:6379"]

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Install PostgreSQL
        run: sudo apt-get -yqq install libpq-dev
      - name: Run bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Setup Database
        run: bin/rails db:prepare
      - name: Seed Database
        run: bin/rails db:seed
      - name: Build and test with rspec
        env:
          COV: true
        run: bundle exec rspec
      - name: Graphql Schema Dump
        run: rake graphql:schema:dump
