default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ratebeez_api_development

test:
  <<: *default
  database: ratebeez_api_test

production:
  <<: *default
  url: <%= ENV["RATEBEEZ_DATABASE_URL"] %>
