source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.4'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.8', '>= 7.0.8.1'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use postgresql as the database for Active Record
gem 'discard', '~> 1.2'
gem 'enumerize'
gem 'paper_trail'
gem 'pg', '~> 1.1'
gem 'pg_search'
gem 'store_model'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'
gem 'rack-attack'
gem 'rack-cors', require: 'rack/cors'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# api
gem 'msgpack'

# background jobs
gem 'good_job'
gem 'postmark-rails'

# authentication

gem 'devise'
gem 'devise-async'
gem 'devise_token_auth', '~> 1.2.2'
gem 'jwt'
gem 'rotp'

# helpers
gem 'bugsnag'
gem 'colorize', require: false
gem 'logdna'
gem 'lograge'
gem 'solid_assert'

# graphql
gem 'bullet', group: 'development'
gem 'globalid'
gem 'goldiloader'
gem 'graphiql-rails', group: :development
gem 'graphql'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]

  # Note this should in development and test if you want to autogenerate spec files
  gem 'rspec'
  gem 'rspec-rails'

  gem 'factory_bot_rails'
  gem 'faker'
  gem 'guard-rspec', require: false

  # profiling
  gem 'ruby-prof', require: false
  gem 'stackprof', require: false
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console'

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  gem 'annotate'
  gem 'deepsort', require: false

  gem 'pry-rails'

  gem 'rubocop', require: false
  gem 'rubocop-graphql', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'ruby-lsp', require: false
  gem 'solargraph', require: false
end

group :test do
  gem 'simplecov', require: false
  gem 'simplecov-console', require: false
  gem 'simplecov-tailwindcss', require: false

  gem 'rspec-set'
  gem 'test-prof', require: false
  gem 'vcr'
  gem 'webmock'
end
